"""add: agregando campo telefgono al modelo de Usuario

Revision ID: 3533fae6cb83
Revises: 82ac9163b6b3
Create Date: 2025-05-16 16:16:37.714430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3533fae6cb83'
down_revision = '82ac9163b6b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
