"""agregando relacion de posts con categorias

Revision ID: 550f53d2e731
Revises: 4143a76ed270
Create Date: 2025-07-25 17:30:11.821868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550f53d2e731'
down_revision = '4143a76ed270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_categoria', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'categorias', ['id_categoria'], ['id_categoria'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_categoria')

    # ### end Alembic commands ###
