"""Migrando los modelos

Revision ID: 92657f0c1767
Revises: 
Create Date: 2025-05-03 18:02:15.188880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92657f0c1767'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multimedia',
    sa.Column('id_multimedia', sa.String(), nullable=False),
    sa.Column('id_post', sa.String(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=50), nullable=True),
    sa.Column('tipo_entidad', sa.String(length=20), nullable=True),
    sa.Column('tipo_archivo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_post'], ['posts.id_post'], ),
    sa.PrimaryKeyConstraint('id_multimedia')
    )
    op.create_table('paises',
    sa.Column('id_pais', sa.String(), nullable=False),
    sa.Column('nombre_pais', sa.String(length=50), nullable=False),
    sa.Column('abrebiatura_pais', sa.String(length=3), nullable=False),
    sa.Column('id_multimedia', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_multimedia'], ['multimedia.id_multimedia'], ),
    sa.PrimaryKeyConstraint('id_pais'),
    sa.UniqueConstraint('abrebiatura_pais')
    )
    op.create_table('posts',
    sa.Column('id_post', sa.String(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('contenido', sa.String(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_pais', sa.String(), nullable=False),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('visible', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_pais'], ['paises.id_pais'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_post')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index('idx_fecha_publicacion', ['fecha_publicacion'], unique=False)

    op.create_table('roles',
    sa.Column('id_rol', sa.String(length=36), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('descripcion')
    )
    op.create_table('categorias',
    sa.Column('id_categoria', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(length=50), nullable=False),
    sa.Column('id_multimedia', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_multimedia'], ['multimedia.id_multimedia'], ),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('id_rol', sa.String(length=36), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_rol'], ['roles.id_rol'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index('idx_email', ['email'], unique=False)

    op.create_table('favoritos',
    sa.Column('id_usuario', sa.String(), nullable=False),
    sa.Column('id_post', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_post'], ['posts.id_post'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_post')
    )
    op.create_table('posts_categorias',
    sa.Column('id_post', sa.String(), nullable=False),
    sa.Column('id_categoria', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_post'], ['posts.id_post'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_post', 'id_categoria')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_categorias')
    op.drop_table('favoritos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index('idx_email')

    op.drop_table('usuarios')
    op.drop_table('categorias')
    op.drop_table('roles')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index('idx_fecha_publicacion')

    op.drop_table('posts')
    op.drop_table('paises')
    op.drop_table('multimedia')
    # ### end Alembic commands ###
