"""Reduciendo campos de post

Revision ID: a418fc3f5002
Revises: 107b07e8ca30
Create Date: 2025-08-05 17:11:04.597786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a418fc3f5002'
down_revision = '107b07e8ca30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paises', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_pais_multimedia', 'multimedia', ['id_multimedia'], ['id_multimedia'], use_alter=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_id_multimedia_fkey', type_='foreignkey')
        batch_op.drop_column('id_multimedia')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_multimedia', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('posts_id_multimedia_fkey', 'multimedia', ['id_multimedia'], ['id_multimedia'], ondelete='CASCADE')

    with op.batch_alter_table('paises', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pais_multimedia', type_='foreignkey')

    # ### end Alembic commands ###
