"""un pequeño cambio

Revision ID: ac9a69722ab2
Revises: 
Create Date: 2025-08-02 20:07:13.766392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9a69722ab2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eslogan_cat', sa.String(length=100), nullable=True))
        batch_op.drop_column('eslogan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eslogan', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.drop_column('eslogan_cat')

    # ### end Alembic commands ###
