"""Relacion entre post y multimedia

Revision ID: c66d64352a1f
Revises: 550f53d2e731
Create Date: 2025-07-28 23:37:51.643468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c66d64352a1f'
down_revision = '550f53d2e731'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_multimedia', sa.String(length=36), nullable=False))
        batch_op.alter_column('id_categoria',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.create_foreign_key(None, 'multimedia', ['id_multimedia'], ['id_multimedia'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id_categoria',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
        batch_op.drop_column('id_multimedia')

    # ### end Alembic commands ###
